//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        public int DealerID { get; set; }
        public string Name { get; set; }
        public string Area { get; set; }
        public int CarID { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
